(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var H0=function(a){a.S("cardstatechange",a.Kg()&&a.Ri()?1:0)},I0=function(a,b){var c=g.La(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},gDa=function(a){var b=g.Fg(a);
a=g.Lg(a);return new g.dg(b.x,b.y,a.width,a.height)},hDa=function(a){return Math.pow(a,3)},iDa=function(a){return 3*a*a-2*a*a*a},L0=function(a){a=g.Oa(a);
delete J0[a];g.Mb(J0)&&K0&&K0.stop()},kDa=function(){K0||(K0=new g.I(function(){jDa()},20));
var a=K0;a.isActive()||a.start()},jDa=function(){var a=g.B();
g.Ab(J0,function(b){lDa(b,a)});
g.Mb(J0)||kDa()},M0=function(a,b,c,d){g.vn.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.i=a;this.I=b;this.duration=c;this.C=d;this.coords=[];this.progress=this.G=0;this.B=null},lDa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.G=1E3/(b-a.B);a.B=b;mDa(a,a.progress);1==a.progress?(a.Ja=0,L0(a),a.onFinish(),a.Er()):a.Ib()&&a.ow()},mDa=function(a,b){"function"===typeof a.C&&(b=a.C(b));
a.coords=Array(a.i.length);for(var c=0;c<a.i.length;c++)a.coords[c]=(a.I[c]-a.i[c])*b+a.i[c]},nDa=function(a,b){g.Il.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.G;this.state=b.Ja},N0=function(a,b,c,d,e){M0.call(this,b,c,d,e);
this.element=a},O0=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
N0.call(this,a,b,c,d,e)},P0=function(a){g.C.call(this);
this.l=a||window;this.i=[]},Q0=function(a){return a.baseUrl||null},R0=function(a,b){return g.He(g.Jc(a,b,void 0),function(c){return!!c})},oDa=function(a,b,c){function d(cb){var lb,vd,Ub,kc=cb.hovercardButton;
if(!kc)return null;kc=kc.subscribeButtonRenderer;if(!kc)return null;var Ze=f(kc.unsubscribedButtonText),$e=f(kc.subscribedButtonText);if(kc.subscribed){var jl=f(kc.subscriberCountWithUnsubscribeText);var ji=f(kc.subscriberCountText)}else jl=f(kc.subscriberCountText),ji=f(kc.subscriberCountWithSubscribeText);var Hf=null;return cb.signinEndpoint&&(Hf=I0(cb,"signinEndpoint","webNavigationEndpointData","url"),Hf||(Hf=null===(Ub=null===(vd=null===(lb=kc.signInEndpoint)||void 0===lb?void 0:lb.commandMetadata)||
void 0===vd?void 0:vd.webCommandMetadata)||void 0===Ub?void 0:Ub.url),!Hf)?null:Ze&&($e||Hf)?{subscribed:kc.subscribed,subscribeText:Ze,subscribeCount:jl,unsubscribeText:$e,unsubscribeCount:ji,enabled:kc.enabled,signinUrl:Hf,classic:cb.useClassicSubscribeButton}:null}
function e(cb){if(cb){var lb=[],vd=cb.videoId;vd&&lb.push("v="+vd);(vd=cb.playlistId)&&lb.push("list="+vd);(cb=cb.startTimeSeconds)&&lb.push("t="+cb);return"/watch?"+lb.join("&")}}
function f(cb){if(!cb)return null;var lb=cb.simpleText;return lb?lb:cb.runs?g.Jc(cb.runs,function(vd){return vd.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=null,r=null,t=null,w=null,x=!1,y=null,F=null,E=null,G=null,J=null;if("VIDEO"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,r=f(b.videoDuration);else if("PLAYLIST"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,t=f(b.playlistLength);else if("CHANNEL"===h){if(x=I0(l,"browseEndpoint","browseId"))w=x,m="/channel/"+w;n=!1;p="new";(x=!!b.isSubscribe)?y=d(b):F=f(b.subscribersText)}else"WEBSITE"===
h?((E=I0(l,"urlEndpoint","url"))&&(m=E),n=!0,p="new",E=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(G=f(b.productPrice)),b.additionalFeesText&&(J=f(b.additionalFeesText)),(n=I0(l,"urlEndpoint","url"))&&(m=n),n=!0,p="new");a=I0(b,"title","accessibility","accessibilityData","label");var H=b.endpoint?b.endpoint.clickTrackingParams:null,Aa="";if(b.metadata){var oa=f(b.metadata);oa&&(Aa=oa)}return{id:"element-"+c,type:h,title:f(b.title),metadata:Aa,callToAction:f(b.callToAction),
dD:b.image,iconUrl:E,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,playlistLength:t,channelId:w,subscribeButton:y,subscribersText:F,isSubscribe:x,targetUrl:m||null,UL:n,yd:H?{itct:H}:null,GQ:p,fq:a?a:null,XL:b.isPlaceholder,impressionUrls:R0(b.impressionUrls||[],Q0),ML:R0(b.hovercardShowUrls||[],Q0),clickUrls:R0(l.loggingUrls||[],Q0),visualElement:g.fu(b.trackingParams),
productPrice:G,additionalFeesText:J}},S0=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:R0(a.impressionUrls||[],Q0),elements:R0(a.elements||[],function(d,e){return oDa(b,d,e)})};
a.trackingParams&&(c.visualElement=g.fu(a.trackingParams));return c},T0=function(a){g.iO.call(this,a);
this.u=this.endscreen=null;this.i={};this.C={};this.B=this.l=null;this.I=[];this.T=!0;this.G=0;a=a.P();this.K=g.UC(a)||g.XC(a);this.events=new g.aO(this);g.D(this,this.events);this.events.L(this.player,g.rG("creatorendscreen"),this.ud);this.events.L(this.player,g.sG("creatorendscreen"),this.jf);this.events.L(this.player,"resize",this.Pa);this.events.L(window,"focus",this.FP);this.load();var b=g.Ce("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.$f(this,function(){g.Ge(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},pDa=function(a){return a.player.getVideoData().C?"current":a.K?"new":"current"},U0=function(a){return"creator-endscreen-editor"===a.player.P().playerStyle},qDa=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.u&&a.u.abort();c={method:"POST",onFinish:function(e){var f=a.u=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=S0(f,pDa(a))));V0(a,f)},
urlParams:{v:c},withCredentials:!0};a.K&&(c.urlParams.ptype="embedded");var d=b.dm;d&&(c.postParams={ad_tracking:d});if(b=g.cja(b))if(b=g.Ec(b),b=g.Ac(b))a.u=g.Zp(b,c)},V0=function(a,b,c){c=void 0===c?!0:c;
a.player.Me("creatorendscreen");a.l&&(a.l.dispose(),a.l=null,a.B.dispose(),a.B=null);for(var d=g.q(Object.values(a.i)),e=d.next();!e.done;e=d.next())e.value.dispose();a.i={};a.C={};0<a.I.length&&(a.I.forEach(function(l){l.dispose()}),a.I.length=0);
a.G=0;if((a.endscreen=b)&&b.elements){c&&rDa(a);c=[];d=new g.oG(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.P().i||(a.l=new g.V({D:"div",J:"ytp-ce-shadow"}),g.ZN(a.player,a.l.element,4),a.B=new g.GM(a.l,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=sDa(a,e);if(f){a.i[e.id]=f;a.C[e.id]=e;g.ZN(a.player,f.element,4);var h=new g.oG(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);tDa(a,f,e)}else g.kt(new g.Zr("buildEndscreenElement null",
e))}a.player.Gd(c);a.Pa()}},rDa=function(a){var b=g.ju(),c=g.lu();
c&&b&&a.endscreen.visualElement&&g.zu(c,b,a.endscreen.visualElement)},sDa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c=a.player.W("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];c={D:"div",ga:["ytp-ce-element","ytp-ce-video"],R:{tabindex:"0","aria-label":b.fq||"","aria-hidden":"true"},N:[{D:"div",J:"ytp-ce-element-shadow"},{D:"div",J:"ytp-ce-covering-image",R:W0(b)},{D:"div",J:"ytp-ce-covering-shadow-top"},{D:"a",J:"ytp-ce-covering-overlay",R:{href:X0(a,b.targetUrl),tabindex:"-1"},N:[{D:"div",ga:["ytp-ce-video-title"].concat(g.la(c)),R:{dir:g.Bn(b.title||
"")},Y:b.title},{D:"div",J:"ytp-ce-video-duration",Y:b.videoDuration||void 0}]}]};c=new g.V(c);break;case "PLAYLIST":c=a.player.W("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];c={D:"div",ga:["ytp-ce-element","ytp-ce-playlist"],R:{tabindex:"0","aria-label":b.fq||"","aria-hidden":"true"},N:[{D:"div",J:"ytp-ce-element-shadow"},{D:"div",J:"ytp-ce-covering-image",R:W0(b)},{D:"div",J:"ytp-ce-covering-shadow-top"},{D:"a",J:"ytp-ce-covering-overlay",R:{href:X0(a,
b.targetUrl),tabindex:"-1"},N:[{D:"div",ga:["ytp-ce-playlist-title"].concat(g.la(c)),R:{dir:g.Bn(b.title||"")},Y:b.title},{D:"div",J:"ytp-ce-playlist-count",N:[{D:"div",J:"ytp-ce-playlist-icon"},{D:"div",J:"ytp-ce-playlist-count-text",Y:b.playlistLength||void 0}]}]}]};c=new g.V(c);break;case "CHANNEL":c={D:"div",ga:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],R:{tabindex:"0","aria-label":b.fq||"","aria-hidden":"true"},N:[{D:"div",J:"ytp-ce-element-shadow"},
{D:"div",J:"ytp-ce-expanding-overlay",N:[{D:"div",J:"ytp-ce-expanding-overlay-hider"},{D:"div",J:"ytp-ce-expanding-overlay-background"},{D:"div",J:"ytp-ce-expanding-overlay-content",N:[{D:"div",J:"ytp-ce-expanding-overlay-body",N:[{D:"div",J:"ytp-ce-expanding-overlay-body-padding",N:[{D:"a",ga:["ytp-ce-channel-title","ytp-ce-link"],R:{href:X0(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Bn(b.title||"")},Y:b.title},b.subscribeButton?{D:"div",J:"ytp-ce-subscribe-container",N:[{D:"div",J:"ytp-ce-channel-subscribe"}]}:
"",b.subscribersText?{D:"div",J:"ytp-ce-channel-subscribers-text",Y:b.subscribersText}:"",b.metadata?{D:"div",ga:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],Y:b.metadata}:""]}]}]}]},{D:"div",J:"ytp-ce-expanding-image",R:W0(b)}]};c=new g.V(c);var d=g.oe(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.K(d,"ytp-ce-subscribe-button");if(a.player.P().i){var e=null;var f=b.yd.itct}else e="endscreen",f=null;e=new g.jP(b.subscribeButton.subscribeText,
b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.I.push(e)}break;case "WEBSITE":c={D:"div",ga:["ytp-ce-element","ytp-ce-website"],R:{tabindex:"0","aria-label":b.fq||"","aria-hidden":"true"},N:[{D:"div",J:"ytp-ce-element-shadow"},{D:"div",J:"ytp-ce-expanding-overlay",N:[{D:"div",J:"ytp-ce-expanding-overlay-hider"},
{D:"div",J:"ytp-ce-expanding-overlay-background"},{D:"div",J:"ytp-ce-expanding-overlay-content",N:[{D:"div",J:"ytp-ce-expanding-overlay-body",N:[{D:"div",J:"ytp-ce-expanding-overlay-body-padding",N:[{D:"div",J:"ytp-ce-website-title",R:{dir:g.Bn(b.title||"")},Y:b.title},{D:"div",J:"ytp-ce-website-metadata",Y:b.metadata},{D:"a",ga:["ytp-ce-website-goto","ytp-ce-link"],R:{href:X0(a,b.targetUrl),target:"_blank",tabindex:"-1"},Y:b.callToAction}]}]}]}]},{D:"div",J:"ytp-ce-expanding-image",R:W0(b)},{D:"div",
J:"ytp-ce-expanding-icon",R:uDa(b.iconUrl)}]};c=new g.V(c);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={D:"div",J:"ytp-ce-merchandise-price-container",N:[{D:"div",J:"ytp-ce-merchandise-price",Y:b.productPrice}]},b.additionalFeesText&&c.N.push({D:"div",J:"ytp-ce-merchandise-additional-fees",Y:b.additionalFeesText})),c={D:"div",ga:["ytp-ce-element","ytp-ce-merchandise"],R:{tabindex:"0","aria-label":b.fq||"","aria-hidden":"true"},N:[{D:"div",J:"ytp-ce-element-shadow"},{D:"div",J:"ytp-ce-expanding-overlay",
N:[{D:"div",J:"ytp-ce-expanding-overlay-hider"},{D:"div",J:"ytp-ce-expanding-overlay-background"},{D:"div",J:"ytp-ce-expanding-overlay-content",N:[{D:"div",J:"ytp-ce-expanding-overlay-body",N:[{D:"div",J:"ytp-ce-expanding-overlay-body-padding",N:[{D:"div",J:"ytp-ce-merchandise-title",R:{dir:g.Bn(b.title||"")},Y:b.title},c,{D:"div",J:"ytp-ce-merchandise-metadata",Y:b.metadata},{D:"a",ga:["ytp-ce-merchandise-goto","ytp-ce-link"],R:{href:X0(a,b.targetUrl),target:"_blank",tabindex:"-1"},Y:b.callToAction}]}]}]}]},
{D:"div",J:"ytp-ce-expanding-image",R:W0(b)},{D:"div",J:"ytp-ce-merchandise-invideo-cta-container",N:[{D:"div",J:"ytp-ce-merchandise-invideo-cta",Y:b.callToAction||void 0}]}]},c=new g.V(c)}b.XL&&g.K(c.element,"ytp-ce-placeholder");return c},W0=function(a){if(a.dD)var b=a.dD.thumbnails;
return uDa(b?b[b.length-1].url:null)},uDa=function(a){return a?{style:"background-image: url("+a+")"}:{}},tDa=function(a,b,c){function d(m){m&&(b.va("blur",function(){"none"!=m.style.display&&a.T&&m.focus()}),b.L(m,"focus",f),b.L(m,"blur",h))}
function e(m){a.G+=m;0<a.G?(g.K(b.element,"ytp-ce-force-expand"),Y0(a,c.id,!0)):(g.sn(b.element,"ytp-ce-force-expand"),g.sn(b.element,"ytp-ce-element-hover"),Y0(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.va("mouseenter",function(){Z0(a,b,c)});
b.va("mouseleave",function(){$0(a,b,c)});
a.player.P().i||b.va("click",function(){g.K(b.element,"ytp-ce-element-hover")});
b.va("click",function(m){vDa(a,c,m)});
b.va("keypress",function(m){vDa(a,c,m)});
b.va("focus",function(){Z0(a,b,c)});
b.va("blur",function(){$0(a,b,c)});
b.va("touchstart",function(){Z0(a,b,c)});
var l=g.qe("ytp-ce-expanding-overlay-hider",b.element);l&&b.L(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.sn(b.element,"ytp-ce-element-hover");g.sn(b.element,"ytp-ce-force-expand")});
b.va("keydown",function(m){a.T=9===m.keyCode&&!m.shiftKey});
d(g.qe("ytp-sb-subscribe",b.element));d(g.qe("ytp-sb-unsubscribe",b.element));b.va("focus",f);b.va("blur",h)},vDa=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.qn(d,"ytp-ce-element");){g.qn(d,"subscribe-label")&&a1(a,b);
if(g.qn(d,"ytp-ce-channel-subscribe"))return;d=g.Ie(d)}if(!d||g.qn(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.i[b.id])$0(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.GQ)a1(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Ec(X0(a,b.targetUrl)),c=g.Ac(c),g.GK(c,void 0,b.yd);else{var e=a.player.getVideoData().C,f=function(){var h=X0(a,b.targetUrl),l=b.yd,m=g.Hp(h);e&&m&&(m.v||m.list)?a.player.Fi(m.v,l,m.list,!1):g.FK(h,l)};
a1(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},X0=function(a,b){var c=a.player.P();
if(b){if(b.startsWith("//"))return c.protocol+":"+b;if(b.startsWith("/"))return g.AD(c)+b}else return"";return b},Z0=function(a,b,c){g.qn(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.K(b.element,"ytp-ce-element-hover"):a.player.P().i?(new g.I(function(){g.K(b.element,"ytp-ce-element-hover")},200)).start():g.K(b.element,"ytp-ce-element-hover"),b1(a,c.ML),Y0(a,c.id,!0))},$0=function(a,b,c){g.sn(b.element,"ytp-ce-element-hover");
g.sn(b.element,"ytp-ce-force-expand");Y0(a,c.id,!1)},Y0=function(a,b,c){a.l&&(c?a.B.show():a.B.hide());
for(var d=g.q(Object.keys(a.i)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.L(a.i[e].element,"ytp-ce-element-shadow-show",c)},b1=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||U0(a))c&&c();else{b=wDa(a,b);var e=0,f=!1,h=new g.I(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.vq(b[a],d)}},a1=function(a,b,c){b1(a,b.clickUrls,c);
(a=g.lu())&&b.UL&&g.Cu(a,b.visualElement)},wDa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push(a.Az(b[e],c));return d},xDa=function(a){return Array.isArray(a)&&a.length?a[0]:a},c1=function(a){return"string"===typeof a?a:""},d1=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},yDa=function(a){this.externalId=a},zDa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.i=d},e1=function(a){return a.value?a.value:null},f1=function(a){if(!a)return null;
var b=g.Ec(c1(a.value));b=g.Ac(b);if(!b)return null;var c=d1(a.target,ADa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new zDa(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},BDa=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},EDa=function(a){if(!a)return null;
var b=d1(a.type,CDa),c=d1(a.trigger,DDa),d=xDa(a.url);d=f1(d?d:null);a=xDa(a.subscribeData);var e=a?a:null;e?(a=c1(e.external_user_id),e=c1(e.subscription_token),a=a&&e?new yDa(a):null):a=null;return b?new BDa(b,c,d,a):null},FDa=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},HDa=function(a){return(a=GDa(a,function(b){return"openUrl"===b.type&&null!=b.url}))?a.url:null},GDa=function(a,b){return g.$a(a.action,b,void 0)},IDa=function(a,b){this.context=a;
this.i=b},h1=function(a){return a.customMessage?g1("div","iv-card-message",a.customMessage):""},i1=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{D:"div",J:"iv-card-image",R:{style:c},N:d}},j1=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.q(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(g1("li","",c.value));return{D:"ul",J:"iv-card-meta-info",N:b}},g1=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Bn(c);return{D:a,R:b,Y:c}},JDa=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.ct&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.ct+");");c.dir=g.Bn(a.customMessage);var d=[{D:"span",Y:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({D:"span",J:"iv-card-link-icon"}));return{D:"div",ga:b,R:c,N:d}},k1=function(a,b,c,d){if(d){b=g.q(b);
for(var e=b.next();!e.done;e=b.next())a.i(e.value,d,c.id,c.yd,c.jg.click,5)}},KDa=function(a,b){this.merchant=a;
this.price=b},LDa=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},MDa=function(a,b){return b?b:LDa(a)?"current":"new"},l1=function(a,b){g.C.call(this);
var c=this;this.element=a;this.context=b;this.Ha=!1;this.wa=new Map;this.Aa=new Map;this.context.F.addEventListener(g.rG("annotations_module"),function(d){(d=c.wa.get(d))&&d.apply(c)});
this.context.F.addEventListener(g.sG("annotations_module"),function(d){(d=c.Aa.get(d))&&d.apply(c)})},m1=function(a,b,c,d,e,f,h){a.context.i.va(b,"click",function(l){a.pw(c,d,e,f||[],h||0,l)});
a.context.i.va(b,"touchstart",function(){a.Ha=!1});
a.context.i.va(b,"touchmove",function(){a.Ha=!0})},NDa=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},n1=function(a,b,c){return{bE:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
bH:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
lv:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},q1=function(a,b,c){l1.call(this,b,c);
var d=this;this.F=a;this.eventId=null;this.ha=this.Ua=this.u=this.ae=!1;this.Z=null;this.cards=[];this.Na=this.K=this.da=this.C=this.ia=this.i=null;this.U=[];this.I=this.Pd=this.fa=null;this.G=0;this.ba=new g.I(g.Ia,c.B.Dd?4E3:3E3);g.D(this,this.ba);this.Ea=new g.I(g.Ia);g.D(this,this.Ea);this.V=new IDa(c,function(e,f,h,l,m,n){m1(d,e,f,h,l,m,n)});
this.T=new g.V({D:"div",J:"iv-drawer",R:{id:"iv-drawer"},N:[{D:"div",J:"iv-drawer-header",R:{"aria-role":"heading"},N:[{D:"span",J:"iv-drawer-header-text"},{D:"button",ga:["iv-drawer-close-button","ytp-button"],R:{"aria-label":"Hide cards",tabindex:"0"}}]},{D:"div",J:"iv-drawer-content"}]});g.D(this,this.T);this.B=this.T.element;this.Fa=new g.GM(this.T,330);g.D(this,this.Fa);this.Ta=g.qe("iv-drawer-header-text",this.B);this.l=g.qe("iv-drawer-content",this.B);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Ua&&o1(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Ua=d.u)&&p1(d)})},ODa=function(a,b){var c=b.data;
c.autoOpenMs&&a.addCueRange(c.autoOpenMs,0x8000000000000,"",function(){o1(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
c.autoCloseMs&&a.addCueRange(c.autoCloseMs,0x8000000000000,"",function(){p1(a)});
var d=c.headerText;g.Ke(a.Ta,d);a.K&&a.K.setAttribute("title",d);c.eventId&&(a.eventId=c.eventId);a.fa=g.fu(c.trackingParams);a.I=g.fu(c.closeTrackingParams);a.Pd=g.fu(c.iconTrackingParams)},PDa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.G;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.G,type:"simple",teaserText:g.T(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,yd:r1(a,c,b,d),sponsored:!1,jg:n1(d,e,d.command),Rj:d.trackingParams?g.fu(d.trackingParams):null,Lh:e.trackingParams?g.fu(e.trackingParams):
null,Pd:f&&f.trackingParams?g.fu(f.trackingParams):null,imageUrl:s1(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.T(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,ct:null,title:d.title?g.T(d.title):"",customMessage:d.callToAction?g.T(d.callToAction):"",url:d.command.urlEndpoint.url?f1({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.command.urlEndpoint.url}):null};t1(a,c)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.G,type:"collaborator",teaserText:g.T(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,yd:r1(a,c,b,d),sponsored:!1,jg:n1(d,e,d.endpoint),Rj:d.trackingParams?g.fu(d.trackingParams):null,Lh:e.trackingParams?g.fu(e.trackingParams):null,Pd:f&&f.trackingParams?g.fu(f.trackingParams):
null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.T(d.customText):null,jG:s1(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.T(d.channelName):"",metaInfo:[d.subscriberCountText?g.T(d.subscriberCountText):""],url:f1({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};t1(a,c)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.G,type:"playlist",teaserText:g.T(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,yd:r1(a,c,b,d),sponsored:!1,jg:n1(d,e,d.action),Rj:d.trackingParams?g.fu(d.trackingParams):null,Lh:e.trackingParams?g.fu(e.trackingParams):null,Pd:f&&f.trackingParams?g.fu(f.trackingParams):
null,us:s1(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.T(d.customMessage):null,playlistVideoCount:g.T(d.playlistVideoCount),title:d.playlistTitle?g.T(d.playlistTitle):"",metaInfo:[d.channelName?g.T(d.channelName):"",d.videoCountText?g.T(d.videoCountText):""],url:f1({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:NDa(d.action)})};t1(a,c)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.videoInfoCardContentRenderer;
e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.G,type:"video",teaserText:g.T(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,yd:r1(a,c,b,d),sponsored:!1,jg:n1(d,e,d.action),Rj:d.trackingParams?g.fu(d.trackingParams):null,Lh:e.trackingParams?g.fu(e.trackingParams):null,Pd:f&&f.trackingParams?g.fu(f.trackingParams):null,us:s1(d.videoThumbnail.thumbnails,258).url,
videoDuration:d.lengthString?g.T(d.lengthString):null,customMessage:d.customMessage?g.T(d.customMessage):null,title:d.videoTitle?g.T(d.videoTitle):"",metaInfo:[d.channelName?g.T(d.channelName):"",d.viewCountText?g.T(d.viewCountText):""],isLiveNow:!!d.badge,url:f1({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:NDa(d.action)})};t1(a,c)}a.G++},s1=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},r1=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},RDa=function(a,b){var c=QDa(a,b);
c&&(c===a.i&&(a.i=null),a.F.removeCueRange(c.card.id),g.Ge(c.ex),g.ib(a.cards,c),a.ht(),u1(a))},o1=function(a,b,c){if(!a.u){a.Fa.show();
a.ia=new g.I(function(){g.K(a.context.F.getRootNode(),g.sT.IV_DRAWER_OPEN)},0);
a.ia.start();a.Z=g.bp(a.l,"mousewheel",function(h){a.ba.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.l.scrollTop+=h});
a.u=!0;var d=g.lu();d&&a.fa&&a.I&&g.Au(d,[a.fa,a.I]);b={TRIGGER_TYPE:b};for(var e=g.q(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.FE||(f.FE=!0,SDa(a.context.logger,f.card.jg.bE,b)),d&&g.Au(d,[f.card.Rj]);H0(a.F);c&&(a.C=new g.I(function(){a.da=a.K;a.Na.focus()},330),a.C.start())}},p1=function(a){a.u&&(a.Fa.hide(),g.cp(a.Z),a.Z=null,g.sn(a.context.F.getRootNode(),g.sT.IV_DRAWER_OPEN),a.u=!1,H0(a.F),a.C&&a.C.stop(),a.C=new g.I(function(){a.da&&(a.da.focus(),a.da=null)},330),a.C.start())},UDa=
function(a){g.rn(a.element,[g.sT.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.ZN(a.F,a.B,5);TDa(a);a.K=g.qe("ytp-cards-button",a.F.getRootNode());a.Na=g.qe("iv-drawer-close-button",a.B);a.ae=!0},TDa=function(a){var b=g.qe("iv-drawer-close-button",a.B);
a.context.i.va(b,"click",a.DK,a);a.context.i.va(a.l,"touchend",function(){a.ba.start()});
a.context.i.va(a.l,"scroll",a.OK,a);a.context.l.subscribe("onHideControls",function(){a.ha=!0});
a.context.l.subscribe("onShowControls",function(){a.ha=!1});
a.context.l.subscribe("onVideoAreaChange",function(){a.ha=g.qn(a.F.getRootNode(),"ytp-autohide")});
a.U.push(g.Ho("iv-button-shown",a.dM,a));a.U.push(g.Ho("iv-button-hidden",a.cM,a));a.U.push(g.Ho("iv-teaser-shown",a.gJ,a));a.U.push(g.Ho("iv-teaser-hidden",a.fM,a));a.U.push(g.Ho("iv-teaser-clicked",a.fJ,a))},t1=function(a,b){a.ae||UDa(a);
RDa(a,b.id);var c=VDa(a,b);if(c){var d={card:b,ex:c.element,FE:!1},e=WDa(a,d);g.qb(a.cards,e,0,d);c.ca(a.l,e);a.ht();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.u||(a.i=d,u1(a),XDa(a,d),o1(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.F.getCurrentTime(),5E3>c&&c>b.startMs&&YDa(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){YDa(a,d)}),u1(a))}},VDa=function(a,b){switch(b.type){case "simple":var c=a.V;
var d=b.displayDomain?{D:"div",J:"iv-card-image-text",Y:b.displayDomain}:void 0;var e=JDa(b);d={D:"div",ga:["iv-card"],N:[{D:"a",J:"iv-click-target",R:{href:b.url?e1(b.url)||"":""},N:[i1(b.imageUrl,d),{D:"div",J:"iv-card-content",N:[g1("h2",void 0,b.title),e]}]}]};d=new g.V(d);k1(c,g.pe("iv-click-target",d.element),b,b.url);return d;case "collaborator":return c=a.V,d={D:"div",ga:["iv-card","iv-card-channel"],N:[{D:"a",ga:["iv-click-target"],R:{href:e1(b.url)||"","data-ytid":b.channelId},N:[i1(b.jG),
{D:"div",J:"iv-card-content",N:[h1(b),{D:"h2",J:"iv-card-primary-link",Y:b.title},j1(b)]}]}]},d=new g.V(d),k1(c,g.pe("iv-click-target",d.element),b,b.url),d;case "playlist":return c=a.V,d={D:"div",ga:["iv-card","iv-card-playlist"],N:[{D:"a",J:"iv-click-target",R:{href:e1(b.url)||""},N:[i1(b.us,{D:"div",J:"iv-card-image-overlay",N:[{D:"span",J:"iv-card-playlist-video-count",Y:b.playlistVideoCount}]}),{D:"div",J:"iv-card-content",N:[h1(b),g1("h2","iv-card-primary-link",b.title),j1(b)]}]}]},d=new g.V(d),
k1(c,g.pe("iv-click-target",d.element),b,b.url),d;case "productListing":c=a.V;var f=!g.eb(b.offers);d=["iv-card"];e="";var h=JDa(b);f&&(d.push("iv-card-product-listing"),e="iv-card-primary-link",h=b.offers[0],f=[],h.price&&f.push({D:"div",J:"iv-card-offer-price",Y:h.price}),h.merchant&&f.push({D:"div",J:"iv-card-offer-merchant",Y:h.merchant}),h={D:"div",N:f});f=b.url?e1(b.url)||"":"";d={D:"div",ga:d,R:{tabindex:"0"},N:[{D:"a",ga:["iv-card-image","iv-click-target"],R:{style:"background-image: url("+
b.imageUrl+");",href:f,"aria-hidden":"true",tabindex:"-1"}},{D:"div",J:"iv-card-content",N:[b.sponsored?{D:"div",J:"iv-card-sponsored",N:["Sponsored",{D:"div",J:"iv-ad-info-container",N:[{D:"div",J:"iv-ad-info",Y:"{{adInfo}}"},{D:"div",J:"iv-ad-info-icon-container",N:[{D:"div",J:"iv-ad-info-icon"},{D:"div",J:"iv-ad-info-callout"}]}]}]}:"",{D:"a",J:"iv-click-target",R:{href:f},N:[g1("h2",e,b.title),h]}]}]};d=new g.V(d);e=g.Ce("span");g.Ke(e,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
d.Bc(e,"adInfo");k1(c,g.pe("iv-click-target",d.element),b,b.url);return d;case "video":return c=a.V,e=b.videoDuration?{D:"span",J:"iv-card-video-duration",Y:b.videoDuration}:void 0,h=b.isLiveNow?{D:"span",ga:["yt-badge","yt-badge-live"],Y:"LIVE NOW"}:null,e={D:"div",ga:["iv-card","iv-card-video"],N:[{D:"a",J:"iv-click-target",R:{href:(null===(d=b.url)||void 0===d?void 0:e1(d))||""},N:[i1(b.us,e),{D:"div",J:"iv-card-content",N:[h1(b),g1("h2","iv-card-primary-link",b.title),j1(b),h]}]}]},d=new g.V(e),
k1(c,g.pe("iv-click-target",d.element),b,b.url),d;default:return null}},WDa=function(a,b){if(0===a.cards.length)return 0;
var c=g.ab(a.cards,function(d){return b.card.startMs>d.card.startMs||b.card.startMs===d.card.startMs&&b.card.timestamp>=d.card.timestamp?!0:!1});
return-1===c?0:c+1},ZDa=function(a){return a.i?"productListing"===a.i.card.type:g.uh(a.cards,function(b){return"productListing"===b.card.type})},u1=function(a){g.L(a.F.getRootNode(),"ytp-cards-shopping-active",ZDa(a))},YDa=function(a,b){if(!g.qn(a.F.getRootNode(),"ytp-cards-teaser-shown")){if(a.i!==b){var c=g.lu(),d=a.i?a.i.card.Pd:a.Pd;
c&&d&&g.Bu(c,[d]);a.i=b;u1(a)}if(c="none"!=a.element.style.display)g.Q(a.context.F.P().experiments,"html5_enable_single_video_vod_ivar_on_pacf")||2!==a.context.F.getPresentingPlayerType()?(c=a.context.F.getPlayerState(),d=0===c&&0===a.context.F.getCurrentTime(),c=1===c||3===c||d):c=1===a.context.F.getAdState();c&&b.card.teaserDurationMs&&a.F.Ap(!0,{teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs});a.Ea.isActive()||((!a.u||!a.ba.isActive()&&a.ha)&&XDa(a,b),a.Ea.start(910+b.card.teaserDurationMs))}},
XDa=function(a,b){if(a.T.Xa){var c=new M0([0,
a.l.scrollTop],[0,b.ex.offsetTop],600,iDa);a.context.u.va(c,"animate",function(d){a.l.scrollTop=d.y});
a.context.u.va(c,"finish",function(d){a.l.scrollTop=d.y});
c.play()}else g.UL(a.T,!0),a.l.scrollTop=b.ex.offsetTop,g.UL(a.T,!1)},v1=function(a){return a.i&&a.i.card?a.i.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},QDa=function(a,b){return g.$a(a.cards,function(c){return c.card.id===b})},w1=function(a,b,c){l1.call(this,a,b);
this.annotation=c;this.isActive=!1},$Da=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},x1=function(a,b,c){w1.call(this,a,b,c);
this.l=null;this.I=!1;this.u=null;this.B=!1;this.i=this.G=this.C=null},aEa=function(a,b){var c=void 0===c?0:c;
var d=gDa(b).width;g.Dg(b,d);c=new O0(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,hDa);g.D(a,c);a.context.u.va(c,"begin",function(){g.Mg(b,!0)});
c.play()},dEa=function(a,b){if(b.channel_name){var c=a.createElement({D:"div",
ga:["iv-branding-context-name"],Y:b.channel_name}),d=a.createElement({D:"div",ga:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.i=new g.jP(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signinUrl,a.context.F),a.i.ca(d));var f=a.createElement({D:"div",ga:["iv-branding-context-subscribe-caret"]}),h=a.createElement({D:"div",ga:["branding-context-container-inner"]});
h.appendChild(f);h.appendChild(c);h.appendChild(d);g.Mg(h,!1);var l=a.createElement({D:"div",ga:["branding-context-container-outer"]});l.appendChild(h);g.vg(l,"right",b.image_width+"px");a.element.appendChild(l);a.u=new g.I(function(){bEa(a,h,l)},500);
g.D(a,a.u);a.context.i.va(a.element,"mouseover",function(){cEa(a,h,l,f,b.image_height)});
a.context.i.va(a.element,"mouseout",function(){a.u.start()})}},cEa=function(a,b,c,d,e){a.u.stop();
if(!a.B){var f=g.Lg(b);a.i||(b.style.width=g.Cg(f.width,!0),c.style.width=g.Cg(f.width,!0));g.vg(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.vg(d,"right","1px");a.B=!0;g.Mg(b,!0);a.C=new g.I(function(){g.K(this.element,"iv-branding-active")},0,a);
a.C.start()}},bEa=function(a,b,c){g.sn(a.element,"iv-branding-active");
a.G=new g.I(function(){g.Mg(b,!1);a.i||(c.style.width=g.Cg(0,!0))},250);
a.G.start();a.B=!1},eEa=function(a,b,c,d,e,f,h){this.i=a;
this.u=b;this.B=c;this.videoData=d;this.logger=e;this.F=f;this.l=h},y1=function(a,b,c){w1.call(this,a,b,c);
var d=this;this.K=this.isCollapsed=this.T=!1;this.G=5E3;this.l=this.u=this.i=this.B=null;this.I=this.createElement({D:"div",ga:["iv-promo-contents"]});this.C=new g.I(function(){d.i.setAttribute("aria-hidden","true");g.Mg(d.u,!1);g.Mg(d.l,!0)},700,this);
g.D(this,this.C)},fEa=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.G=b.collapsedelay_ms||a.G;var d=["iv-promo","iv-promo-inactive"];a.element.setAttribute("aria-hidden","true");a.element.setAttribute("aria-label","Promotion");a.element.tabIndex=0;var e=HDa(a.annotation),f=b.image_url;if(f){var h=a.createElement({D:"div",ga:["iv-promo-img","iv-click-target"]});f=a.createElement({D:"img",R:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&
!b.is_live?(f=a.createElement({D:"span",J:"iv-promo-video-duration",Y:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({D:"span",J:"iv-promo-playlist-length",Y:b.playlist_length.toString()}),h.appendChild(f));e&&m1(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({D:"a",J:"iv-promo-txt"}),g.ed(f,e1(e)),a.i=f):a.i=a.createElement({D:"div",J:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({D:"p",N:[{D:"strong",
Y:b.text_line_1}]});var m=a.createElement({D:"p",N:[{D:"span",J:"iv-promo-link",Y:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({D:"button",ga:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({D:"button",ga:["iv-button","iv-promo-button"],N:[{D:"span",J:"iv-button-content",Y:f}]});var p=a.createElement({D:"div",J:"iv-promo-button-container"});p.appendChild(f);e&&m1(a,a.element,e,a.annotation.id,b.session_data,void 0,c)}g.K(a.i,
"iv-click-target");e&&m1(a,a.i,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({D:"p",N:[{D:"span",Y:b.text_line_1}]}),m=a.createElement({D:"p",N:[{D:"strong",Y:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({D:"span",ga:["yt-badge","iv-promo-badge-live"],Y:"LIVE NOW"})),g.K(a.i,"iv-click-target"),e&&m1(a,a.i,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.i.appendChild(l);m&&a.i.appendChild(m);a.I.appendChild(a.i);p&&a.I.appendChild(p);
c=a.createElement({D:"div",J:"iv-promo-actions"});a.l=a.createElement({D:"button",ga:["iv-promo-expand","ytp-button"]});a.l.title="Expand";a.context.i.va(a.l,"click",function(r){z1(a,5E3,r)});
c.appendChild(a.l);g.Mg(a.l,!1);a.context.i.va(a.element,"mouseover",a.vL,a);a.context.i.va(a.element,"mouseout",a.uL,a);a.context.i.va(a.element,"touchend",function(r){z1(a,5E3,r)});
a.u=a.createElement({D:"button",ga:["iv-promo-close","ytp-button"]});a.u.title="Close";a.context.i.va(a.u,"click","cta"===a.annotation.style&&b.text_line_3?a.pL:a.oL,a);c.appendChild(a.u);g.rn(a.element,d);h&&(a.element.appendChild(h),n&&h.appendChild(n));a.element.appendChild(a.I);a.element.appendChild(c)},z1=function(a,b,c){c.stopPropagation();
gEa(a);hEa(a,b);a.i.focus()},iEa=function(a){a.isCollapsed||a.K||a.B||(g.K(a.element,"iv-promo-collapsed"),a.isCollapsed=!0,a.C.start())},gEa=function(a){a.C.stop();
a.isCollapsed&&(g.tn(a.element,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.i&&a.i.removeAttribute("aria-hidden"),g.Mg(a.l,!1),g.Mg(a.u,!0))},hEa=function(a,b){a.B||(a.B=g.Mm(function(){A1(this);
iEa(this)},b,a))},A1=function(a){a.B&&(g.z.clearTimeout(a.B),a.B=null)},jEa=function(a){this.F=a},SDa=function(a,b,c){b&&(c?B1(a,b.map(function(d){return g.fn(d,c)})):B1(a,b))},B1=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.q(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.vq(m,f);d&&(e++,0!==d&&a.F.sendVideoStatsEngageEvent(d,f))},C1=function(a){g.iO.call(this,a);
var b=this;this.T=!1;this.loadNumber=0;this.I={};this.logger=new jEa(this.player);this.C=new g.aO(this);this.G=this.u=null;this.events=new g.aO(this);this.K=this.i=null;this.U=[];g.D(this,this.C);this.C.L(this.player,"onVideoAreaChange",function(){b.S("onVideoAreaChange")});
this.C.L(this.player,"onHideControls",function(){b.S("onHideControls")});
this.C.L(this.player,"onShowControls",function(){b.S("onShowControls")});
this.C.L(this.player,"resize",function(d){b.S("resize",d)});
this.C.L(this.player,"presentingplayerstatechange",function(d){b.S("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.hJ,this);this.subscribe("resize",this.Hu,this);this.player.P().K.subscribe("vast_info_card_add",this.VF,this);g.D(this,this.events);this.V=this.createElement({D:"div",J:"video-custom-annotations"});this.l=new g.V({D:"div",ga:["ytp-player-content","ytp-iv-player-content"]});g.D(this,this.l);g.ZN(this.player,this.l.element,4);this.l.hide();this.B=new g.V({D:"div",ga:["ytp-iv-video-content"]});g.D(this,this.B);a=this.createElement({D:"div",J:"video-annotations"});
a.appendChild(this.V);this.B.element.appendChild(a);this.Fn()&&this.load();var c=this.createElement({D:"style"});(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(c);g.$f(this,function(){g.Ge(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},kEa=function(a){a=a.createElement({D:"div",
ga:["annotation","annotation-type-custom"]});g.Mg(a,!1);return a},lEa=function(a,b){var c=!b.isCued()&&!g.U(b,1024);
g.UL(a.l,c);g.UL(a.B,c)},mEa=function(a,b,c){a.T=!0;
a.G=g.Zp(b,c)},nEa=function(a,b){for(var c={},d=g.q(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Ma(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(nEa(a,e))}return c},qEa=function(a){var b=a.player.getVideoData();
if(b.Z){var c=a.player.P().K.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.Tp(h)&&h.responseXML?h.responseXML:null)&&D1(a,h)}};
g.sp()&&(d.onFinish=oEa(a,d.onFinish));d.postParams={ic_only:"1"};pEa(d,c);a.T=!0;g.Zp(b.Z,d)}}},pEa=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.qq&&(a.postParams.ic_coll=b.qq);b.lt&&(a.postParams.ic_xml=b.lt);b.ys&&(a.postParams.ic_track=b.ys)},rEa=function(a){var b=new g.V({D:"div"});
g.Mg(b.element,!1);var c=new q1(a.player,b.element,E1(a));g.D(c,b);b.ca(a.l.element);c.Xr();return c},E1=function(a){if(!a.K){var b=new P0(a);
g.D(a,b);var c=new g.u_(a);g.D(a,c);a.K=new eEa(b,c,a.player.P(),a.player.getVideoData(),a.logger,a.player,a.Dd)}return a.K},D1=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.lu();if(e){var f=g.ju();f&&g.ru(g.Qo("use_default_events_client")?void 0:g.ct,e,f,[g.fu(d)])}}d=b.getElementsByTagName("annotation");for(e=0;e<d.length;e++){var h=nEa(a,d[e]);f=null;try{if(h){var l=h.id,m=/.+/;var n="string"===typeof l&&null!=m&&null!=l&&l.match(m)?l:"";var p=d1(h.type,sEa),r=d1(h.style,tEa),t=c1(h.data),w=0!==t.length?JSON.parse(t):{};var x=h.action;h=EDa;if(null==x)var y=null;else if(g.La(x)){m=[];for(var F=g.q(x),E=F.next();!E.done;E=
F.next()){var G=h(E.value);G&&m.push(G)}y=m}else{var J=h(x);y=J?[J]:[]}f=n&&p?new FDa(n,p,r,y,w):null}else f=null}catch(vd){}if(f)if("branding"===f.type||"promotion"===f.type){h=a;m=f;var H=kEa(h),Aa=null;switch(m.type){case "branding":if(h.player.P().Gb)break;h.l.element.appendChild(H);Aa=new x1(H,E1(h),m);break;case "promotion":g.ZN(h.player,H,4),Aa=new y1(H,E1(h),m)}Aa&&Aa.Xr();if(h=Aa)g.D(a,h),a.I[f.id]=h}else if("card"===f.type||"drawer"===f.type){a.i||(a.i=rEa(a),g.D(a,a.i));if("card"===f.type){c=
a.i;var oa=f&&f.data&&f.data.card_type;h=f.data;if(oa)switch(m=h.tracking||{},m={bE:m.impression,click:m.click,close:m.close,bH:m.teaser_impression,lv:m.teaser_click},H=h.tracking_params||{},Aa=null,oa){case "collaborator":f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,yd:h.session_data||{},sponsored:h.sponsored||!1,jg:m,Rj:H.card?g.fu(H.card):null,Lh:H.teaser?g.fu(H.teaser):null,Pd:H.icon?
g.fu(H.icon):null,channelId:h.channel_id,customMessage:h.custom_message?h.custom_message:null,jG:h.image_url,title:h.title,metaInfo:h.meta_info,url:f1({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url})};t1(c,f);break;case "playlist":f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,yd:h.session_data||{},sponsored:h.sponsored||!1,jg:m,Rj:H.card?g.fu(H.card):null,
Lh:H.teaser?g.fu(H.teaser):null,Pd:H.icon?g.fu(H.icon):null,us:h.image_url,playlistVideoCount:h.playlist_video_count,customMessage:h.custom_message?h.custom_message:null,title:h.title,metaInfo:h.meta_info,url:f1({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url})};t1(c,f);break;case "productListing":h.signin_url&&(Aa=f1({target:"current",value:h.signin_url}));oa=[];for(var cb=h.offers||[],lb=0;lb<cb.length;lb++)oa.push(new KDa(g.ld(cb[lb].merchant),g.ld(cb[lb].price)));
f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,yd:h.session_data||{},sponsored:h.sponsored||!1,jg:m,Rj:H.card?g.fu(H.card):null,Lh:H.teaser?g.fu(H.teaser):null,Pd:H.icon?g.fu(H.icon):null,imageUrl:h.image_url,displayDomain:h.display_domain?h.display_domain:null,showLinkIcon:!!h.show_link_icon,ct:h.button_icon_url?h.button_icon_url:null,title:h.title,customMessage:h.custom_message?h.custom_message:
null,url:f1({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url}),V3:Aa,U3:h.signin_title?h.signin_title:void 0,T3:h.signin_message?h.signin_message:void 0,offers:oa};t1(c,f);break;case "simple":f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,yd:h.session_data||{},sponsored:h.sponsored||!1,jg:m,Rj:H.card?g.fu(H.card):null,Lh:H.teaser?g.fu(H.teaser):null,Pd:H.icon?
g.fu(H.icon):null,imageUrl:h.image_url,displayDomain:h.display_domain?h.display_domain:null,showLinkIcon:!!h.show_link_icon,ct:h.button_icon_url?h.button_icon_url:null,title:h.title,customMessage:h.custom_message?h.custom_message:null,url:f1({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url})};t1(c,f);break;case "video":f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||
!1,yd:h.session_data||{},sponsored:h.sponsored||!1,jg:m,Rj:H.card?g.fu(H.card):null,Lh:H.teaser?g.fu(H.teaser):null,Pd:H.icon?g.fu(H.icon):null,us:h.image_url,videoDuration:h.video_duration||null,customMessage:h.custom_message?h.custom_message:null,title:h.title,metaInfo:h.meta_info,isLiveNow:!!h.is_live_now,url:f1({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url})},t1(c,f)}}else ODa(a.i,f);c=!0}}c&&(H0(a.player),a.Hu())},uEa=function(a,b){var c=!1;
a.i||(a.i=rEa(a),g.D(a,a.i));for(var d=g.q(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(PDa(a.i,e.cardRenderer),c=!0);c&&(c=a.i,d=b.headerText?g.T(b.headerText):"",g.Ke(c.Ta,d),c.K&&c.K.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.fa=b.trackingParams?g.fu(b.trackingParams):null,c.I=b.closeButton.infoCardIconRenderer.trackingParams?g.fu(b.closeButton.infoCardIconRenderer.trackingParams):null,c.Pd=b.icon.infoCardIconRenderer.trackingParams?
g.fu(b.icon.infoCardIconRenderer.trackingParams):null,H0(a.player),a.Hu())},vEa=function(a,b,c,d,e){if(!a.player.P().Gb){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new BDa("openUrl","click",new zDa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0),null));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;var l;b=b.subscribeButton.subscribeButtonRenderer;var m,n;h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.T(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.T(b.subscriberCountText))):(b.subscriberCountText&&(e=g.T(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.T(b.subscriberCountWithSubscribeText)));var p=b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url?b.signInEndpoint.webNavigationEndpointData.url:(null===(n=null===(m=null===(l=b.signInEndpoint)||void 0===l?void 0:l.commandMetadata)||void 0===m?void 0:m.webCommandMetadata)||void 0===n?void 0:n.url)||"";l={subscribeText:g.T(b.unsubscribedButtonText),subscribeCount:e||"",unsubscribeText:g.T(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:p};d.standalone_subscribe_button_data=
l}f=new FDa(c,"branding","branding",f,d);l=kEa(a);a.l.element.appendChild(l);f=new x1(l,E1(a),f);f.Xr();g.D(f,f);a.I[c]=f}},oEa=function(a,b){return function(c){for(var d=[],e=0;e<arguments.length;++e)d[e-0]=arguments[e];
a.ka()||(d.unshift(b),b=g.Pa.apply(window,d),a.U.push(g.qp(b)))}},wEa=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.SN.prototype.Ap=g.ca(15,function(a,b){var c=g.tO(this.Ra());c&&c.Ap(a,b)});
var J0={},K0=null;g.Ra(M0,g.vn);g.k=M0.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.Ja)this.progress=0,this.coords=this.i;else if(this.Ib())return!1;L0(this);this.startTime=a=g.B();-1==this.Ja&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.B=this.startTime;this.progress||this.Gu();this.sh("play");-1==this.Ja&&this.sh("resume");this.Ja=1;var b=g.Oa(this);b in J0||(J0[b]=this);kDa();lDa(this,a);return!0};
g.k.stop=function(a){L0(this);this.Ja=0;a&&(this.progress=1);mDa(this,this.progress);this.sh("stop");this.Er()};
g.k.pause=function(){this.Ib()&&(L0(this),this.Ja=-1,this.sh("pause"))};
g.k.aa=function(){0==this.Ja||this.stop(!1);this.sh("destroy");M0.Ad.aa.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.ow=function(){this.sh("animate")};
g.k.sh=function(a){this.dispatchEvent(new nDa(a,this))};
g.Ra(nDa,g.Il);g.Ra(N0,M0);N0.prototype.u=g.Ia;N0.prototype.ow=function(){this.u();N0.Ad.ow.call(this)};
N0.prototype.Er=function(){this.u();N0.Ad.Er.call(this)};
N0.prototype.Gu=function(){this.u();N0.Ad.Gu.call(this)};
g.Ra(O0,N0);O0.prototype.u=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.u(P0,g.C);P0.prototype.va=function(a,b,c,d){c=(0,g.A)(c,d||this.l);a=g.bp(a,b,c);this.i.push(a);return a};
P0.prototype.Oy=function(a,b,c,d){c=(0,g.A)(c,d||this.l);a=g.kp(a,b,c);this.i.push(a);return a};
P0.prototype.Db=function(a){g.cp(a);g.ib(this.i,a)};
P0.prototype.aa=function(){g.cp(this.i);this.i.length=0;g.C.prototype.aa.call(this)};g.u(T0,g.iO);g.k=T0.prototype;g.k.load=function(){g.iO.prototype.load.call(this);if(!U0(this)){var a=g.dja(this.player.getVideoData());a?(a=S0(a,pDa(this)),V0(this,a,!1)):qDa(this)}};
g.k.unload=function(){V0(this,null);this.u&&(this.u.abort(),this.u=null);g.iO.prototype.unload.call(this)};
g.k.Ee=function(a,b){if(!U0(this))return null;if("loadCustomEndscreenRenderer"===a){var c=S0(b,"new");V0(this,c);return!0}return null};
g.k.getOptions=function(){return U0(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.Pa=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<xEa.length;f++){var h=Math.abs(b.width-xEa[f]);if(-1===e||d>=h)e=f,d=h}d=yEa[e];this.l&&g.vg(this.l.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.i[f],
h=this.C[f],e&&h){var l=h.width*c/h.aspectRatio;f=Math.round(l*a.height);var m=a.left+Math.round(h.left*a.width),n=a.top+Math.round(h.top*a.height);g.Kg(e.element,Math.round(h.width*a.width),f);g.Dg(e.element,m,n);g.tn(e.element,zEa);m=h.left+h.width/2;h=h.top+l/2;g.K(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.tn(e.element,yEa);g.K(e.element,d);(e=g.oe(document,"div","ytp-ce-expanding-overlay-body",
e.element)[0])&&g.vg(e,"height",f+"px")}}}}};
g.k.ud=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())b1(this,this.endscreen.impressionUrls),(a=g.lu())&&this.endscreen.visualElement&&g.tu(a,this.endscreen.visualElement,void 0);else{a=a.getId().substring(15);var b=this.i[a],c=this.C[a];g.K(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.K(b,"ytp-ce-shown");b1(this,c.impressionUrls);(b=g.lu())&&g.tu(b,c.visualElement,void 0);this.player.P().u&&this.player.ra("endscreenelementshown",
a)}};
g.k.jf=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.i[a];g.sn(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.sn(b,"ytp-ce-shown");this.player.P().u&&this.player.ra("endscreenelementhidden",a)}};
g.k.FP=function(a){var b=this;a.target===window&&(new g.I(function(){for(var c=g.q(Object.values(b.i)),d=c.next();!d.done;d=c.next())g.tn(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.k.Az=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})};
var xEa=[346,426,470,506,570,640,853,1280,1920],yEa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),zEa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var ADa={xU:"current",TZ:"new"};var CDa={CLOSE:"close",f_:"openUrl",iK:"subscribe"},DDa={rS:"click",CLOSE:"close",QV:"hidden",v0:"rollOut",w0:"rollOver",b1:"shown"};var tEa={OR:"anchored",KH:"branding",CHANNEL:"channel",vU:"cta",TV:"highlightText",SW:"label",PLAYLIST:"playlist",S_:"popup",m1:"speech",iK:"subscribe",F1:"title",VIDEO:"video",O2:"website"},sEa={KH:"branding",gS:"card",KU:"drawer",SV:"highlight",qY:"marker",b0:"promotion",TEXT:"text",U2:"widget"};g.u(l1,g.C);g.k=l1.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.oG(a,b,{id:c});a.namespace="annotations_module";d&&this.wa.set(a,d);e&&this.Aa.set(a,e);this.context.F.Gd([a])};
g.k.Xr=function(){this.context.l.subscribe("resize",this.ht,this)};
g.k.pw=function(a,b,c,d,e,f){if(this.Ha)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.Ge(this.element)};
g.k.ht=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=e1(a);if(f){var h=MDa(f,a.target),l=function(){a.i&&e.context.F.pauseVideo();var m=e.context.videoData.C||!1,n=g.Hp(f||"");m&&n&&(n.v||n.list)?e.context.F.Fi(n.v,b,n.list,!1):g.GK(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);B1(this.context.logger,c,l,d);LDa(f)||(c=g.lu(),d=b.itct,c&&d&&g.Cu(c,g.fu(d)))}};
g.k.aa=function(){this.wa.clear();this.Aa.clear();g.C.prototype.aa.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.D(this,a);return a.element};g.u(q1,l1);g.k=q1.prototype;g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.F.getRootNode())?(a=g.Lg(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.ht=function(){var a=this.isAvailable();g.Mg(this.element,a);g.L(this.context.F.getRootNode(),g.sT.IV_DRAWER_ENABLED,a);H0(this.F)};
g.k.destroy=function(){this.F.Ap(!1);try{this.F.getRootNode().removeChild(this.B)}catch(a){}g.Io(this.U);g.cp(this.Z);this.ia&&this.ia.dispose();this.C&&this.C.dispose();l1.prototype.destroy.call(this)};
g.k.DK=function(){if(this.u){B1(this.context.logger,v1(this).jg.close);var a=g.lu();a&&this.I&&g.Cu(a,this.I);p1(this)}};
g.k.OK=function(){g.L(this.B,"iv-drawer-scrolled",0<this.l.scrollTop)};
g.k.dM=function(){var a=g.lu(),b=v1(this);b=b?b.Pd:this.Pd;a&&b&&g.Au(a,[b])};
g.k.cM=function(){var a=g.lu(),b=v1(this);b=b?b.Pd:this.Pd;a&&b&&g.Bu(a,[b])};
g.k.gJ=function(){var a=v1(this);B1(this.context.logger,a.jg.bH);var b=g.lu();b&&a&&g.Au(b,[a.Lh,a.Pd])};
g.k.fM=function(){var a=g.lu(),b=v1(this);a&&b&&g.Bu(a,[b.Lh])};
g.k.fJ=function(a){var b=v1(this),c=g.lu();this.i?a?(a=this.context.logger,B1(a,b.jg.lv),a.F.sendVideoStatsEngageEvent(4,void 0),c&&b.Lh&&g.Cu(c,b.Lh)):(a=this.context.logger,B1(a,b.jg.lv),a.F.sendVideoStatsEngageEvent(4,void 0),c&&b.Pd&&g.Cu(c,b.Pd)):(a=this.context.logger,B1(a,b.jg.lv),a.F.sendVideoStatsEngageEvent(4,void 0),c&&this.Pd&&g.Cu(c,this.Pd))};g.u(w1,l1);w1.prototype.Xr=function(){l1.prototype.Xr.call(this);$Da(this)};
w1.prototype.show=function(){l1.prototype.show.call(this);var a=g.lu(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Au(a,[g.fu(b.itct)])};
w1.prototype.hide=function(){l1.prototype.hide.call(this);var a=g.lu(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Bu(a,[g.fu(b.itct)])};g.u(x1,w1);
x1.prototype.show=function(){if(!this.isActive){w1.prototype.show.call(this);if(!this.I){g.K(this.element,"iv-branding");var a=this.annotation.data;this.l=this.createElement({D:"img",ga:["branding-img","iv-click-target"],R:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.Mg(this.l,!1);var b=this.createElement({D:"div",ga:["branding-img-container"]});b.appendChild(this.l);this.element.appendChild(b);(b=HDa(this.annotation))&&m1(this,this.l,b,this.annotation.id,
a.session_data);dEa(this,a);this.I=!0}g.Mg(this.element,!0);this.isActive=!0;this.l&&aEa(this,this.l)}};
x1.prototype.hide=function(){this.isActive&&(w1.prototype.hide.call(this),g.Mg(this.element,!1),this.isActive=!1)};
x1.prototype.destroy=function(){this.i&&(this.i.dispose(),this.i=null);w1.prototype.destroy.call(this)};g.u(y1,w1);g.k=y1.prototype;g.k.show=function(){this.isActive||(w1.prototype.show.call(this),this.T||(fEa(this),this.T=!0),g.Mg(this.element,!0),g.Mm(function(){g.sn(this.element,"iv-promo-inactive")},100,this),this.element.removeAttribute("aria-hidden"),this.isActive=!0,A1(this),gEa(this),hEa(this,this.G))};
g.k.hide=function(){this.isActive&&(g.K(this.element,"iv-promo-inactive"),this.isActive=!1,this.element.setAttribute("aria-hidden","true"))};
g.k.pw=function(a,b,c,d,e,f){return this.isCollapsed?!1:w1.prototype.pw.call(this,a,b,c,d,e,f)};
g.k.vL=function(a){this.K=!0;z1(this,500,a)};
g.k.uL=function(){this.K=!1;iEa(this)};
g.k.oL=function(a){a.stopPropagation();this.hide()};
g.k.pL=function(a){a.stopPropagation();A1(this);this.isCollapsed=!0;g.K(this.element,"iv-promo-collapsed-no-delay");this.C.start()};
g.k.destroy=function(){this.C.dispose();w1.prototype.destroy.call(this)};g.u(C1,g.iO);g.k=C1.prototype;g.k.Ee=function(a,b){if(!wEa(this.player.P().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.t_(b);c&&D1(this,c);return!0;case "removeCustomAnnotationById":return b&&this.i&&(RDa(this.i,b),H0(this.player)),!0}return null};
g.k.getOptions=function(){return wEa(this.player.P().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Fn=function(){var a=this.player.P(),b=this.player.getVideoData();return b.C&&a.pfpChazalUi?!1:1===(a.annotationsLoadPolicy||b.annotationsLoadPolicy)&&!b.aE||a.K.get(b.videoId)||g.fJ(b)||g.gJ(b)?!0:!1};
g.k.Hu=function(){if(this.B){var a=this.player.Ga().getVideoContentRect(!0);g.Kg(this.B.element,a.width,a.height);g.Dg(this.B.element,a.left,a.top)}if(this.i){var b=this.player.gj();a=this.i;b=b.width;g.L(a.B,"iv-drawer-small",426>=b);g.L(a.B,"iv-drawer-big",1280<=b)}};
g.k.hJ=function(a){lEa(this,a.state);g.U(a.state,2)&&(this.Kg()&&this.Ri()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Ap(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.G=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.Tp(h)&&h.responseXML?h.responseXML:null)&&(D1(b,h),g.K(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.iO.prototype.load.call(this);lEa(this,this.player.Sa());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.sp()&&(a=oEa(this,a));var e={format:"XML",onFinish:a,onError:function(){b.G=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.P().K.get(d);f&&pEa(e,f);f=f&&(f.lt||f.qq);if(!c.Ek||f)c.Z?mEa(this,c.Z,e):(this.u=function(){b.La(e)},this.player.addEventListener("videodatachange",this.u));
g.ZN(this.player,this.B.element,4);this.Hu();(f=g.fJ(c))&&uEa(this,f);(f=g.gJ(c))&&f.featuredChannel&&vEa(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.La=function(a){var b=this.player.getVideoData();b.Z&&(this.u&&(this.player.removeEventListener("videodatachange",this.u),this.u=null),mEa(this,b.Z,a))};
g.k.unload=function(){this.player.Me("annotations_module");for(var a=g.q(Object.keys(this.I)),b=a.next();!b.done;b=a.next())this.I[b.value].destroy();this.K=null;this.i&&(this.i.destroy(),this.i=null,H0(this.player));this.T=!1;this.G&&(this.G.abort(),this.G=null);this.I={};this.l.hide();g.iO.prototype.unload.call(this);this.B.detach();this.u&&(this.player.removeEventListener("videodatachange",this.u),this.u=null)};
g.k.VF=function(a){a===this.player.getVideoData().videoId&&(this.loaded?qEa(this):this.load())};
g.k.Kg=function(){return!!this.i&&this.i.isAvailable()};
g.k.Ri=function(){this.Kg();return!!this.i&&this.i.u};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.Kg();this.i&&(a?c?o1(this.i,c,b):o1(this.i,"YOUTUBE_DRAWER_AUTO_OPEN",b):p1(this.i))};
g.k.Ap=function(a,b){this.player.S(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.aa=function(){this.player.P().K.unsubscribe("vast_info_card_add",this.VF,this);g.sn(this.player.getRootNode(),g.sT.IV_DRAWER_OPEN);for(var a=this.U,b=0,c=a.length;b<c;b++)g.tp(a[b]);this.U.length=0;g.iO.prototype.aa.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.D(this,a);return a.element};g.oO.annotations_module=C1;g.oO.creatorendscreen=T0;})(_yt_player);
