(function(g){var window=this;var hGa=function(a,b){a.ra("onAutonavCoundownStarted",b)},q3=function(a,b,c){var d=b.Ka();
g.L(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.se(c?c:"mqdefault.jpg");var f=null,h=null;b instanceof g.uI&&(b.lengthText?(f=b.lengthText||null,h=b.ku||null):b.lengthSeconds&&(f=g.zM(b.lengthSeconds),h=g.zM(b.lengthSeconds,!0)));var l=!!e;e=l&&"RD"===(new g.cO(e.substr(0,2),e.substr(2))).type;var m=b instanceof g.uI?b.isLivePlayback:null,n=b instanceof g.uI?b.isUpcoming:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:
b.author,aria_label:b.jq||g.yK("Watch $TITLE",{TITLE:b.title}),duration:f,timestamp:h,url:b.wl(),is_live:m,is_upcoming:n,is_list:l,is_mix:e,background:c?"background-image: url("+c+")":"",views_and_publish_time:d.shortViewCount?d.shortViewCount+" \u2022 "+d.publishedTimeText:d.publishedTimeText,autoplayAlternativeHeader:b.mq};b instanceof g.dO&&(d.playlist_length=b.length);a.update(d)},r3=function(a){var b=a.P(),c=b.l;
g.V.call(this,{D:"a",J:"ytp-autonav-suggestion-card",R:{href:"{{url}}",target:c?b.C:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},N:[{D:"div",ga:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],R:{style:"{{background}}"},N:[{D:"div",R:{"aria-label":"{{timestamp}}"},ga:["ytp-autonav-timestamp"],Y:"{{duration}}"},{D:"div",ga:["ytp-autonav-live-stamp"],Y:"Live"},{D:"div",
ga:["ytp-autonav-upcoming-stamp"],Y:"Upcoming"},{D:"div",J:"ytp-autonav-list-overlay",N:[{D:"div",J:"ytp-autonav-mix-text",Y:"Mix"},{D:"div",J:"ytp-autonav-mix-icon"}]}]},{D:"div",ga:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],Y:"{{title}}"},{D:"div",ga:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],Y:"{{author}}"},{D:"div",ga:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],Y:"{{views_and_publish_time}}"}]});this.F=a;this.suggestion=
null;this.i=c;this.va("click",this.onClick);this.va("keypress",this.l)},t3=function(a,b){b=void 0===b?!1:b;
g.V.call(this,{D:"div",J:"ytp-autonav-endscreen-countdown-container"});var c=this;this.C=b;this.l=0;var d=a.P(),e=d.l;this.F=a;this.suggestion=null;this.i=new g.V({D:"div",J:"ytp-autonav-endscreen-upnext-container",R:{"aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},N:[{D:"div",J:"ytp-autonav-endscreen-upnext-header"},{D:"div",J:"ytp-autonav-endscreen-upnext-alternative-header",Y:"{{autoplayAlternativeHeader}}"},
{D:"a",J:"ytp-autonav-endscreen-link-container",R:{href:"{{url}}",target:e?d.C:""},N:[{D:"div",J:"ytp-autonav-endscreen-upnext-thumbnail",R:{style:"{{background}}"},N:[{D:"div",R:{"aria-label":"{{timestamp}}"},ga:["ytp-autonav-timestamp"],Y:"{{duration}}"},{D:"div",ga:["ytp-autonav-live-stamp"],Y:"Live"},{D:"div",ga:["ytp-autonav-upcoming-stamp"],Y:"Upcoming"}]},{D:"div",J:"ytp-autonav-endscreen-video-info",N:[{D:"div",J:"ytp-autonav-endscreen-premium-badge"},{D:"div",J:"ytp-autonav-endscreen-upnext-title",
Y:"{{title}}"},{D:"div",J:"ytp-autonav-endscreen-upnext-author",Y:"{{author}}"},{D:"div",J:"ytp-autonav-view-and-date",Y:"{{views_and_publish_time}}"},{D:"div",J:"ytp-autonav-author-and-view",Y:"{{author_and_views}}"}]}]}]});g.D(this,this.i);this.i.ca(this.element);e||this.L(this.i.ea("ytp-autonav-endscreen-link-container"),"click",this.CB);this.F.Fb(this.element,this,115127);this.F.Fb(this.i.ea("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.V({D:"div",J:"ytp-autonav-overlay"});
g.D(this,this.overlay);this.overlay.ca(this.element);this.u=new g.V({D:"div",J:"ytp-autonav-endscreen-button-container"});g.D(this,this.u);this.u.ca(this.element);this.cancelButton=new g.V({D:"button",ga:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button"],R:{"aria-label":"Cancel autoplay"},Y:"Cancel"});g.D(this,this.cancelButton);this.cancelButton.ca(this.u.element);this.cancelButton.va("click",this.uJ,this);this.F.Fb(this.cancelButton.element,this,115129);this.playButton=
new g.V({D:"a",ga:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button"],R:{href:"{{url}}",role:"button","aria-label":"Play next video"},Y:"Play Now"});g.D(this,this.playButton);this.playButton.ca(this.u.element);this.playButton.va("click",this.CB,this);this.F.Fb(this.playButton.element,this,115130);this.B=new g.I(function(){s3(c)},500);
g.D(this,this.B);this.BB();this.L(a,"autonavvisibility",this.BB)},s3=function(a){var b=u3(a),c=Math.min(a.l?Date.now()-a.l:0,b);
v3(a,Math.ceil((b-c)/1E3));500>=b-c&&a.Ug()?a.select(!0):a.Ug()&&a.B.start()},u3=function(a){var b=a.F.Um();
return 0<=b?b:g.P(a.F.P().experiments,"autoplay_time")||1E4},v3=function(a,b){b=void 0===b?-1:b;
var c=a.i.ea("ytp-autonav-endscreen-upnext-header");g.Ee(c);if(0<=b){var d=String(b),e="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],f="Up next in $SECONDS".indexOf(e);if(0<=f){c.appendChild(g.De("Up next in $SECONDS".slice(0,f)));var h=g.Ce("span");g.pn(h,"ytp-autonav-endscreen-upnext-header-countdown-number");g.Ke(h,d);c.appendChild(h);c.appendChild(g.De("Up next in $SECONDS".slice(f+e.length)));return}}g.Ke(c,"Up next")},w3=function(a,b){g.V.call(this,{D:"div",
ga:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},y3=function(a){g.V.call(this,{D:"div",
ga:["ytp-upnext","ytp-player-content"],R:{"aria-label":"{{aria_label}}"},N:[{D:"div",J:"ytp-cued-thumbnail-overlay-image",R:{style:"{{background}}"}},{D:"span",J:"ytp-upnext-top",N:[{D:"span",J:"ytp-upnext-header",Y:"Up Next"},{D:"span",J:"ytp-upnext-title",Y:"{{title}}"},{D:"span",J:"ytp-upnext-author",Y:"{{author}}"}]},{D:"a",J:"ytp-upnext-autoplay-icon",R:{role:"button",href:"{{url}}","aria-label":"Play next video"},N:[{D:"svg",R:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},N:[{D:"circle",
J:"ytp-svg-autoplay-circle",R:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{D:"circle",J:"ytp-svg-autoplay-ring",R:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{D:"path",J:"ytp-svg-fill",R:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{D:"span",J:"ytp-upnext-bottom",N:[{D:"span",J:"ytp-upnext-cancel"},{D:"span",J:"ytp-upnext-paused",Y:"Autoplay is paused"}]}]});
this.api=a;this.cancelButton=null;this.C=this.ea("ytp-svg-autoplay-ring");this.u=this.notification=this.i=this.suggestion=null;this.B=new g.I(this.nt,5E3,this);this.l=0;var b=this.ea("ytp-upnext-cancel");this.cancelButton=new g.V({D:"button",ga:["ytp-upnext-cancel-button","ytp-button"],R:{tabindex:"0","aria-label":"Cancel autoplay"},Y:"Cancel"});g.D(this,this.cancelButton);this.cancelButton.va("click",this.vJ,this);this.cancelButton.ca(b);this.cancelButton&&this.api.Fb(this.cancelButton.element,this,
115129);g.D(this,this.B);this.api.Fb(this.element,this,18788);b=this.ea("ytp-upnext-autoplay-icon");this.L(b,"click",this.wJ);this.api.Fb(b,this,115130);this.DB();this.L(a,"autonavvisibility",this.DB);this.L(a,"mdxnowautoplaying",this.RN);this.L(a,"mdxautoplaycanceled",this.SN);this.L(a,"mdxautoplayupnext",this.uH);x3(this)&&(a=(a=g.VN(this.api.Ra()))?a.kL():null)&&this.uH(a);g.L(this.element,"ytp-upnext-mobile",this.api.P().i)},x3=function(a){return 3===a.api.getPresentingPlayerType()},iGa=function(a,
b){return b?b:0<=a.api.Um()?a.api.Um():g.P(a.api.P().experiments,"autoplay_time")||1E4},z3=function(a,b){var c=iGa(a,b),d=Math,e=d.min;
var f=(0,g.N)()-a.l;d=e.call(d,f,c);c=0===c?1:Math.min(d/c,1);a.C.setAttribute("stroke-dashoffset",""+-211*(c+1));1<=c&&a.Ug()&&!x3(a)?a.select(!0):a.Ug()&&a.i.start()},A3=function(a){w3.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=this.suggestions=null;this.table=new g.V({D:"div",J:"ytp-suggestion-panel",N:[{D:"div",ga:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],Y:"More videos"}]});this.I=new g.V({D:"div",J:"ytp-suggestions-container"});this.videos=[];this.u=null;this.C=this.G=!1;this.l=new t3(this.player);g.D(this,this.l);this.l.ca(this.element);a.getVideoData().qc?this.i=this.l:(this.i=new y3(a),g.ZN(this.player,this.i.element,4),g.D(this,this.i));this.overlay=new g.V({D:"div",
J:"ytp-autonav-overlay-cancelled-state"});g.D(this,this.overlay);this.overlay.ca(this.element);this.B=new g.aO(this);g.D(this,this.B);g.D(this,this.table);this.table.ca(this.element);this.table.show();g.D(this,this.I);this.I.ca(this.table.element);this.hide()},jGa=function(a,b){return g.Jc(b.suggestions,function(c){c=g.YQ(a.player.P(),c);
g.D(a,c);return c})},B3=function(a){var b=a.rd();
b!==a.C&&(a.C=b,a.player.S("autonavvisibility"),a.C?(a.l!==a.i&&a.l.hide(),a.table.hide()):(a.l!==a.i&&a.l.show(),a.table.show()))},C3=function(a){w3.call(this,a,"subscribecard-endscreen");
this.i=new g.V({D:"div",J:"ytp-subscribe-card",N:[{D:"img",J:"ytp-author-image",R:{src:"{{profilePicture}}"}},{D:"div",J:"ytp-subscribe-card-right",N:[{D:"div",J:"ytp-author-name",Y:"{{author}}"},{D:"div",J:"html5-subscribe-button-container"}]}]});g.D(this,this.i);this.i.ca(this.element);var b=a.getVideoData();this.subscribeButton=new g.jP("Subscribe",null,"Unsubscribe",null,!0,!1,b.Eg,b.subscribed,"trailer-endscreen",null,null,a);g.D(this,this.subscribeButton);this.subscribeButton.ca(this.i.ea("html5-subscribe-button-container"));
this.L(a,"videodatachange",this.oa);this.oa();this.hide()},D3=function(a){var b=a.P(),c=g.GA||g.yg?{style:"will-change: opacity"}:void 0,d=b.l,e=["ytp-videowall-still"];
b.i&&e.push("ytp-videowall-show-text");g.V.call(this,{D:"a",ga:e,R:{href:"{{url}}",target:d?b.C:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},N:[{D:"div",J:"ytp-videowall-still-image",R:{style:"{{background}}"}},{D:"span",J:"ytp-videowall-still-info",N:[{D:"span",J:"ytp-videowall-still-info-bg",N:[{D:"span",J:"ytp-videowall-still-info-content",R:c,N:[{D:"span",J:"ytp-videowall-still-info-title",Y:"{{title}}"},{D:"span",J:"ytp-videowall-still-info-author",
Y:"{{author_and_views}}"},{D:"span",J:"ytp-videowall-still-info-live",Y:"Live"},{D:"span",J:"ytp-videowall-still-info-duration",Y:"{{duration}}"}]}]}]},{D:"span",ga:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],N:[{D:"span",J:"ytp-videowall-still-listlabel-icon"},"Playlist",{D:"span",J:"ytp-videowall-still-listlabel-length",N:[" (",{D:"span",Y:"{{playlist_length}}"},")"]}]},{D:"span",ga:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],N:[{D:"span",
J:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{D:"span",J:"ytp-videowall-still-listlabel-length",Y:" (50+)"}]}]});this.suggestion=null;this.l=d;this.api=a;this.i=new g.aO(this);g.D(this,this.i);this.va("click",this.onClick);this.va("keypress",this.u);this.i.L(a,"videodatachange",this.La);a.Ng(this.element,this);this.La()},E3=function(a){w3.call(this,a,"videowall-endscreen");
var b=this;this.F=a;this.u=0;this.stills=[];this.B=this.videoData=this.suggestions=null;this.C=this.I=!1;this.K=null;this.l=new g.aO(this);g.D(this,this.l);this.G=new g.I(function(){g.K(b.element,"ytp-show-tiles")},0);
g.D(this,this.G);var c=new g.V({D:"button",ga:["ytp-button","ytp-endscreen-previous"],R:{"aria-label":"Previous"},N:[g.YL()]});g.D(this,c);c.ca(this.element);c.va("click",this.AJ,this);this.table=new g.RL({D:"div",J:"ytp-endscreen-content"});g.D(this,this.table);this.table.ca(this.element);c=new g.V({D:"button",ga:["ytp-button","ytp-endscreen-next"],R:{"aria-label":"Next"},N:[g.ZL()]});g.D(this,c);c.ca(this.element);c.va("click",this.zJ,this);a.getVideoData().qc?this.i=new t3(a,!0):this.i=new y3(a);
g.D(this,this.i);g.ZN(this.player,this.i.element,4);this.hide()},F3=function(a){return g.$N(a.player)&&a.lq()&&!a.B},kGa=function(a,b){return g.Jc(b.suggestions,function(c){c=g.YQ(a.F.P(),c);
g.D(a,c);return c})},G3=function(a){var b=a.rd();
b!==a.I&&(a.I=b,a.player.S("autonavvisibility"))},H3=function(a){g.iO.call(this,a);
var b=this;this.endScreen=null;this.i=this.l=this.u=!1;this.listeners=new g.aO(this);g.D(this,this.listeners);this.env=a.P();lGa(a)?(this.u=!0,mGa(this),this.i?this.endScreen=new A3(a):this.endScreen=new E3(this.player)):this.env.Ac?this.endScreen=new C3(this.player):this.endScreen=new w3(this.player);g.D(this,this.endScreen);g.ZN(this.player,this.endScreen.element,4);nGa(this);this.listeners.L(a,"videodatachange",this.La,this);this.listeners.L(a,g.rG("endscreen"),function(c){b.ud(c)});
this.listeners.L(a,g.sG("endscreen"),function(c){b.jf(c)})},mGa=function(a){var b=a.player.getVideoData();
if(!b||a.i===b.Xe&&a.l===b.qc)return!1;a.i=b.Xe;a.l=b.qc;return!0},lGa=function(a){a=a.P();
return a.jb&&!a.Ac},nGa=function(a){a.player.Me("endscreen");
var b=a.player.getVideoData();b=new g.oG(Math.max(1E3*(b.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.oG(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});a.player.Gd([b,c])};
g.SN.prototype.Um=g.ca(4,function(){return this.app.Um()});
g.gW.prototype.Um=g.ca(3,function(){return this.getVideoData().wG});
g.u(r3,g.V);r3.prototype.select=function(){(this.F.Fi(this.suggestion.Ka().videoId,this.suggestion.yd,this.suggestion.getPlaylistId(),void 0,void 0,this.suggestion.Gx||void 0)||this.F.W("web_player_endscreen_double_log_fix_killswitch"))&&this.F.sb(this.element)};
r3.prototype.onClick=function(a){g.BO(a,this.F,this.i,this.suggestion.yd||void 0)&&this.select()};
r3.prototype.l=function(a){switch(a.keyCode){case 13:case 32:g.ip(a)||(this.select(),g.hp(a))}};
r3.prototype.Td=function(a){g.L(this.element,"ytp-suggestion-card-with-margin",a)};g.u(t3,g.V);g.k=t3.prototype;g.k.bq=function(a){this.suggestion!==a&&(this.suggestion=a,q3(this.i,a),this.playButton.xa("url",this.suggestion.wl()),this.Td())};
g.k.Td=function(){var a=this.F.gj(!0,this.F.isFullscreen());g.L(this.element,"ytp-autonav-endscreen-small-mode",this.Ke(a));g.L(this.element,"ytp-autonav-endscreen-is-premium",!!this.suggestion&&!!this.suggestion.gv);g.L(this.F.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!this.F.rd());g.L(this.F.getRootNode(),"countdown-running",this.Ug());g.L(this.element,"ytp-player-content",this.F.rd());g.vg(this.overlay.element,{width:a.width+"px"});if(!this.Ug()){this.F.rd()?v3(this,Math.round(u3(this)/
1E3)):v3(this);a=!!this.suggestion&&!!this.suggestion.mq;var b=this.F.rd()||!a;g.L(this.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!b&&a);g.L(this.element,"ytp-autonav-endscreen-upnext-no-alternative-header",b&&!a);g.UL(this.u,this.F.rd())}};
g.k.Ug=function(){return 0<this.l};
g.k.Fp=function(){this.Ug()||(this.l=Date.now(),s3(this),hGa(this.F,u3(this)),g.L(this.F.getRootNode(),"countdown-running",this.Ug()))};
g.k.xn=function(){this.Ak();s3(this)};
g.k.Ak=function(){this.Ug()&&(this.B.stop(),this.l=0)};
g.k.select=function(a){this.F.nextVideo(!1,void 0===a?!1:a);this.Ak()};
g.k.CB=function(a){g.BO(a,this.F)&&(a.currentTarget===this.playButton.element?this.F.sb(this.playButton.element):a.currentTarget===this.i.ea("ytp-autonav-endscreen-link-container")&&(a=this.i.ea("ytp-autonav-endscreen-link-container"),this.F.Ma(a,!0),this.F.sb(a)),this.select())};
g.k.uJ=function(){this.F.sb(this.cancelButton.element);g.UN(this.F,!0)};
g.k.BB=function(){var a=this.F.rd();this.C&&this.Xa!==a&&g.UL(this,a);this.Td();this.F.Ma(this.element,a);this.F.Ma(this.cancelButton.element,a);this.F.Ma(this.i.ea("ytp-autonav-endscreen-link-container"),a);this.F.Ma(this.playButton.element,a)};
g.k.Ke=function(a){return 400>a.width||459>a.height};g.u(w3,g.V);g.k=w3.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.lq=function(){return!1};
g.k.rd=function(){return!1};
g.k.rE=function(){return!1};g.u(y3,g.V);g.k=y3.prototype;g.k.nt=function(){this.notification&&(this.B.stop(),this.Db(this.u),this.u=null,this.notification.close(),this.notification=null)};
g.k.bq=function(a){this.suggestion=a;q3(this,a,"hqdefault.jpg")};
g.k.DB=function(){g.UL(this,this.api.rd());this.api.Ma(this.element,this.api.rd());this.api.Ma(this.ea("ytp-upnext-autoplay-icon"),this.api.rd());this.cancelButton&&this.api.Ma(this.cancelButton.element,this.api.rd())};
g.k.eO=function(){window.focus();this.nt()};
g.k.Fp=function(a){var b=this;this.Ug()||(g.Jo("a11y-announce","Up Next "+this.suggestion.title),this.l=(0,g.N)(),this.i=new g.I(function(){z3(b,a)},25),z3(this,a),hGa(this.api,iGa(this,a)));
g.sn(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.V.prototype.hide.call(this)};
g.k.Ug=function(){return!!this.i};
g.k.xn=function(){this.Ak();this.l=(0,g.N)();z3(this);g.K(this.element,"ytp-upnext-autoplay-paused")};
g.k.Ak=function(){this.Ug()&&(this.i.dispose(),this.i=null)};
g.k.select=function(a){a=void 0===a?!1:a;if(g.Q(this.api.P().experiments,"autonav_notifications")&&a&&window.Notification&&document.hasFocus){var b=Notification.permission;"default"===b?Notification.requestPermission():"granted"!==b||document.hasFocus()||(b=this.suggestion.Ka(),this.nt(),this.notification=new Notification("Up Next",{body:b.title,icon:b.se()}),this.u=this.L(this.notification,"click",this.eO),this.B.start())}this.Ak();this.api.nextVideo(!1,a)};
g.k.wJ=function(a){!g.Je(this.cancelButton.element,g.dp(a))&&g.BO(a,this.api)&&(this.api.rd()&&this.api.sb(this.ea("ytp-upnext-autoplay-icon")),this.select())};
g.k.vJ=function(){this.api.rd()&&this.cancelButton&&this.api.sb(this.cancelButton.element);g.UN(this.api,!0)};
g.k.RN=function(a){x3(this);this.show();this.Fp(a)};
g.k.uH=function(a){x3(this);this.suggestion&&this.suggestion.Ka().videoId===a.Ka().videoId||this.bq(a)};
g.k.SN=function(){x3(this);this.Ak();this.hide()};
g.k.aa=function(){this.Ak();this.nt();g.V.prototype.aa.call(this)};g.u(A3,w3);g.k=A3.prototype;g.k.create=function(){w3.prototype.create.call(this);this.B.L(this.player,"appresize",this.Td);this.B.L(this.player,"onVideoAreaChange",this.Td);this.B.L(this.player,"videodatachange",this.La);this.B.L(this.player,"autonavchange",this.EB);this.B.L(this.player,"autonavcancel",this.xJ);this.La()};
g.k.show=function(){w3.prototype.show.call(this);(this.G||this.u&&this.u!==this.videoData.clientPlaybackNonce)&&g.UN(this.player,!1);g.$N(this.player)&&this.lq()&&!this.u?(B3(this),2===this.videoData.autonavState?this.player.P().W("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.i.select(!0):this.i.Fp():3===this.videoData.autonavState&&this.i.xn()):(g.UN(this.player,!0),B3(this));this.Td()};
g.k.hide=function(){w3.prototype.hide.call(this);this.i.xn();B3(this)};
g.k.Td=function(){var a=this.player.gj(!0,this.player.isFullscreen());B3(this);this.l.Td();g.L(this.element,"ytp-autonav-cancelled-small-mode",this.Ke(a));g.L(this.element,"ytp-autonav-cancelled-tiny-mode",this.fu(a));g.L(this.element,"ytp-autonav-cancelled-mini-mode",400>=a.width||360>=a.height);this.overlay&&g.vg(this.overlay.element,{width:a.width+"px"});if(!this.C){a=g.q(this.videos.entries());for(var b=a.next();!b.done;b=a.next()){b=g.q(b.value);var c=b.next().value;b.next().value.Td(1===c%2)}}};
g.k.La=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((this.suggestions=jGa(this,a))&&this.suggestions.length)for(this.i.bq(this.suggestions[0]),this.i!==this.l&&this.l.bq(this.suggestions[0]),a=0;a<oGa.length;++a){var b=oGa[a];if(this.suggestions&&this.suggestions[b]){this.videos[a]=new r3(this.player);var c=this.videos[a];b=this.suggestions[b];c.suggestion!==b&&(c.suggestion=b,q3(c,b));g.D(this,this.videos[a]);this.videos[a].ca(this.I.element)}}this.Td()}};
g.k.EB=function(a){1===a?(this.G=!1,this.u=this.videoData.clientPlaybackNonce,this.i.Ak(),this.Xa&&this.Td()):(this.G=!0,this.rd()&&(2===a?this.i.Fp():3===a&&this.i.xn()))};
g.k.xJ=function(a){a?this.EB(1):(this.u=null,this.G=!1)};
g.k.lq=function(){return 1!==this.videoData.autonavState};
g.k.Ke=function(a){return(910>a.width||459>a.height)&&!this.fu(a)&&!(400>=a.width||360>=a.height)};
g.k.fu=function(a){return 800>a.width&&!(400>=a.width||360>=a.height)};
g.k.rd=function(){return this.Xa&&g.$N(this.player)&&this.lq()&&!this.u};
var oGa=[1,3,2,4];g.u(C3,w3);C3.prototype.oa=function(){var a=this.player.getVideoData();this.i.update({profilePicture:a.dg,author:a.author});this.subscribeButton.channelId=a.Eg;var b=this.subscribeButton;a.subscribed?b.l():b.u()};g.u(D3,g.V);D3.prototype.select=function(){(this.api.Fi(this.suggestion.Ka().videoId,this.suggestion.yd,this.suggestion.getPlaylistId(),void 0,void 0,this.suggestion.Gx||void 0)||this.api.W("web_player_endscreen_double_log_fix_killswitch"))&&this.api.sb(this.element)};
D3.prototype.onClick=function(a){g.BO(a,this.api,this.l,this.suggestion.yd||void 0)&&this.select()};
D3.prototype.u=function(a){switch(a.keyCode){case 13:case 32:g.ip(a)||(this.select(),g.hp(a))}};
D3.prototype.La=function(){var a=this.api.getVideoData(),b=this.api.P();this.l=a.C?!1:b.l};g.u(E3,w3);g.k=E3.prototype;g.k.create=function(){w3.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.suggestions=kGa(this,a),this.videoData=a);this.Td();this.l.L(this.player,"appresize",this.Td);this.l.L(this.player,"onVideoAreaChange",this.Td);this.l.L(this.player,"videodatachange",this.La);this.l.L(this.player,"autonavchange",this.qw);this.l.L(this.player,"autonavcancel",this.yJ);a=this.videoData.autonavState;a!==this.K&&this.qw(a);this.l.L(this.element,"transitionend",this.rP)};
g.k.destroy=function(){g.St(this.l);g.Zf(this.stills);this.stills=[];this.suggestions=null;w3.prototype.destroy.call(this);g.sn(this.element,"ytp-show-tiles");this.G.stop();this.K=this.videoData.autonavState};
g.k.lq=function(){return 1!==this.videoData.autonavState};
g.k.show=function(){w3.prototype.show.call(this);g.sn(this.element,"ytp-show-tiles");this.player.P().i?this.G.Pg():this.G.start();(this.C||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.UN(this.player,!1);F3(this)?(G3(this),2===this.videoData.autonavState?this.player.P().W("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.i.select(!0):this.i.Fp():3===this.videoData.autonavState&&this.i.xn()):(g.UN(this.player,!0),G3(this))};
g.k.hide=function(){w3.prototype.hide.call(this);this.i.xn();G3(this)};
g.k.rP=function(a){g.dp(a)===this.element&&this.Td()};
g.k.Td=function(){if(this.suggestions&&this.suggestions.length){g.K(this.element,"ytp-endscreen-paginate");var a=this.F.gj(!0,this.F.isFullscreen()),b=g.PN(this.F);b&&(b=b.te()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),h=Math.max(a.height/54,2),l=this.suggestions.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<h);){var p=b/2,r=e/2,t=b<=f-2&&n>=r*m,w=e<=h-2&&n>=p*m;if((p+1)/r*d/c>c/(p/(r+1)*d)&&w)n-=p*m,e+=2;else if(t)n-=
r*m,b+=2;else if(w)n-=p*m,e+=2;else break}d=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m=Math.floor(Math.min(a.width,m*c));n=Math.floor(Math.min(a.height,n*c));a=this.table.element;g.Kg(a,m,n);g.vg(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});this.i.bq(this.suggestions[0]);this.i instanceof t3&&this.i.Td();g.L(this.element,"ytp-endscreen-takeover",F3(this));G3(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(h=0;h<e;h++)if(p=c,r=0,d&&f>=b-2&&h>=e-2?
r=1:0===h%2&&0===f%2&&(2>h&&2>f?0===h&&0===f&&(r=2):r=2),p=g.$d(p+this.u,l),0!==r){t=this.stills[c];t||(t=new D3(this.player),this.stills[c]=t,a.appendChild(t.element));w=Math.floor(n*h/e);var x=Math.floor(m*f/b),y=Math.floor(n*(h+r)/e)-w-4,F=Math.floor(m*(f+r)/b)-x-4;g.Dg(t.element,x,w);g.Kg(t.element,F,y);g.vg(t.element,"transitionDelay",(h+f)/20+"s");g.L(t.element,"ytp-videowall-still-mini",1===r);g.L(t.element,"ytp-videowall-still-large",2<r);r=t;p=this.suggestions[p];r.suggestion!==p&&(r.suggestion=
p,t=r.api.P(),w=g.qn(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",q3(r,p,w),g.OC(t)&&(t=p.wl(),t=g.Id(t,g.fP("emb_rel_end")),r.xa("url",t)),(p=(p=p.yd)&&p.itct)&&r.api.Vl(r.element,p));c++}g.L(this.element,"ytp-endscreen-paginate",c<l);for(b=this.stills.length-1;b>=c;b--)e=this.stills[b],g.Ge(e.element),g.Yf(e);this.stills.length=c}};
g.k.La=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.u=0,this.suggestions=kGa(this,a),this.videoData=a,this.Td())};
g.k.zJ=function(){this.u+=this.stills.length;this.Td()};
g.k.AJ=function(){this.u-=this.stills.length;this.Td()};
g.k.rE=function(){return this.i.Ug()};
g.k.qw=function(a){1===a?(this.C=!1,this.B=this.videoData.clientPlaybackNonce,this.i.Ak(),this.Xa&&this.Td()):(this.C=!0,this.Xa&&F3(this)&&(2===a?this.i.Fp():3===a&&this.i.xn()))};
g.k.yJ=function(a){if(a){for(a=0;a<this.stills.length;a++)this.F.Ma(this.stills[a].element,!0);this.qw(1)}else this.B=null,this.C=!1;this.Td()};
g.k.rd=function(){return this.Xa&&F3(this)};g.u(H3,g.iO);g.k=H3.prototype;g.k.Fn=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!lGa(this.player)||b;var c=a.Qc||g.YC(a.B),d=this.player.Mq();a=a.mutedAutoplay;return b&&!c&&!d&&!a};
g.k.rd=function(){return this.endScreen.rd()};
g.k.RL=function(){return this.rd()?this.endScreen.rE():!1};
g.k.aa=function(){this.player.Me("endscreen");g.iO.prototype.aa.call(this)};
g.k.load=function(){var a=this.player.getVideoData();var b=a.oD;if(b&&b.videoId){var c=this.player.Ra().Yc.get("heartbeat");a&&a.suggestions&&a.suggestions.length&&b.videoId===a.suggestions[0].id&&!a.UB?a=!1:(this.player.Fi(b.videoId,void 0,void 0,!0,!0,b),c&&c.nu("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0)}else a=!1;a||(g.iO.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.iO.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.ud=function(a){this.Fn()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.k.jf=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.k.La=function(){nGa(this);this.u&&mGa(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.i?this.endScreen=new A3(this.player):this.endScreen=new E3(this.player),g.D(this,this.endScreen),g.ZN(this.player,this.endScreen.element,4))};g.oO.endscreen=H3;})(_yt_player);
